name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run type checking
        run: npm run type-check

  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check

  build-library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Upload library build
        uses: actions/upload-artifact@v4
        with:
          name: library-build
          path: dist/
          retention-days: 1

  build-widget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build widget
        run: npm run build:widget

      - name: Upload widget build
        uses: actions/upload-artifact@v4
        with:
          name: widget-build
          path: |
            dist/embed/widget.*
            dist/embed/style.css
          retention-days: 1

  test-widget:
    runs-on: ubuntu-latest
    needs: build-widget
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download widget build
        uses: actions/download-artifact@v4
        with:
          name: widget-build
          path: dist/embed/

      - name: Verify downloaded files
        run: |
          echo "Contents of dist directory:"
          ls -la dist/
          echo "Contents of dist/embed directory:"
          ls -la dist/embed/
          echo "Checking for required files..."
          test -f dist/embed/widget.umd.js || (echo "widget.umd.js not found!" && exit 1)
          test -f dist/embed/style.css || (echo "style.css not found!" && exit 1)
          echo "Contents of root directory:"
          ls -la
          echo "Checking test-widget-embed.html exists:"
          test -f test-widget-embed.html && echo "test-widget-embed.html found" || echo "test-widget-embed.html NOT found"

      - name: Install Playwright
        run: npx playwright install chromium

      - name: Run widget tests
        run: npm run test:ci:only

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
